# 监听本地的端口
listen: :8889

# 使用redis来存放access_token
redis:
  host: 127.0.0.1:6379

# 微信公众号相关配置
officialAccountConfig:
  appID: xxx
  appSecret: xxx
  token: xxx
  encodingAESKey: xxx

oracle:
  user: xxx
  password: xxx
  host: ip
  port: 1521
  sid: dlnu10g

runtime:
  log:
    logRootPath: '/runtime/logs/'
    disableTimestamp: false
    timestampFormat: '2006-01-02 15:04:05'
